import './Rules.css'; // Ensure this path is correct
import React from 'react';
import Nav2 from './Nav2.js';
const Rules = () => {
  return (
    <div>
      <Nav2/>
   
    <div className='rpage'>
      <p>
THE EVENT "NEXUS VERSE" PRESENTS A SERIES OF INTERCONNECTED QUESTIONS, WHERE EACH ANSWER LEADS TO THE NEXT, GUIDING YOU STEP-BY-STEP TO THE ULTIMATE SOLUTION.
<br/>
THIS EVENT WILL BE CONDUCTED IN 2 DAYS AND THERE WILL BE A CHANCE TO GET BONUS POINT IN EACH DAY.
<br/>
<hr/>
1.THERE ARE A TOTAL OF 3 ROUNDS IN THE EVENT-
<br/>
ROUND 1-IT WILL HAVE 7 QUESTIONS WITH 4 CLUES. TIME FOR ANSWERING EACH CLUE WILL BE 90 SECONDS.
<br/>
ROUND 2-IT WILL HAVE 7 QUESTIONS WITH 4 CLUES. TIME FOR ANSWERING EACH CLUE WILL BE 70 SECONDS.
<br/>
ROUND 3-IT WILL HAVE 5 QUESTIONS WITH 3 CLUES. TIME FOR ANSWERING EACH CLUE WILL BE 50 SECONDS.
<br/>
DAY 1-PARTICIPANTS CAN ACCESS ONLY ROUND 1 AND ROUND 2. AFTER COMPLETING THESE ROUNDS, BONUS ROUND 1 (TRICKY TRIVIA) UNLOCKS, OFFERING A CHANCE TO EARN BONUS POINTS FOR THE DAY.
<br/>
DAY 2-ROUND 3 WILL BE ACCESSIBLE ON THE DAY 2 HOWEVER NEW PARTICIPANTS CAN ALSO JOIN AND THEY WILL BE ABLE TO PLAY ALL ROUNDS ON THE DAY 2. BONUS ROUND 2 WILL ALSO BE THERE FOR SCORING THE BONUS POINT OF THE DAY.
<br/>
3.THE ANSWER MUST BE WRITTEN IN CAPITAL LETTERS ONLY. THE HIGHEST SCORER WILL BE ON THE TOP OF THE LEADERBOARD.
<br/>
4. ANYONE FROM NIT DURGAPUR OR OUTSIDE CAN PARTICIPATE IN THE EVENT.
<br/>
5.IN ORDER TO GET CONSIDERED IN THE COMPETITION, YOU HAVE TO FOLLOW ALL SOCIAL MEDIA HANDLES OF RADIONITROZ, FAILING TO DO SO, THEIR PARTICIPATION WILL NOT BE CONSIDERED.
</p>
    </div>
    </div>
  );
};

export default Rules;
